; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=memcpyopt -inline-memcpy-threshold=128 -S -verify-memoryssa | FileCheck %s
 
 
declare void @llvm.memcpy.p0.p0.i64(ptr nocapture, ptr nocapture, i64, i1) nounwind
declare void @foo(ptr nocapture noalias readonly)
 
 
; Version llvm.memcpy into llvm.memcpy.inline when size is smaller than the threshold.
; During lowering llvm.memcpy.inline could be lowered directly into sve load/stores.
define void @memcpy_versioning(i64 %size) {
; CHECK-LABEL: @memcpy_versioning(
; CHECK-NEXT:    [[VAL:%.*]] = alloca i8, align 4
; CHECK-NEXT:    store i32 42, ptr [[VAL]], align 4
; CHECK-NEXT:    [[VAL1:%.*]] = alloca i8, align 4
; CHECK-NEXT:    [[MEMCPY_SIZE_CMP:%.*]] = icmp ule i64 [[SIZE:%.*]], 128
; CHECK-NEXT:    br i1 [[MEMCPY_SIZE_CMP]], label [[CALL_MEMCPY_INLINE:%.*]], label [[CALL_MEMCPY_ORIGINAL:%.*]]
; CHECK:       call.memcpy.original:
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[VAL1]], ptr align 4 [[VAL]], i64 [[SIZE]], i1 false)
; CHECK-NEXT:    br label [[CALL_MEMCPY_MERGE:%.*]]
; CHECK:       call.memcpy.inline:
; CHECK-NEXT:    call void @llvm.memcpy.inline.p0.p0.i64(ptr align 4 [[VAL1]], ptr align 4 [[VAL]], i64 [[SIZE]], i1 false)
; CHECK-NEXT:    br label [[CALL_MEMCPY_MERGE]]
; CHECK:       call.memcpy.merge:
; CHECK-NEXT:    store i32 13, ptr [[VAL]], align 4
; CHECK-NEXT:    call void @foo(ptr [[VAL1]])
; CHECK-NEXT:    ret void
;
  %val = alloca i8, align 4
  store i32 42, ptr %val
  %val1 = alloca i8, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %val1, ptr align 4 %val, i64 %size, i1 false)
  store i32 13, ptr %val
  call void @foo(ptr %val1)
  ret void
}
 
; Here memcpy is at the beginning of a BB.
; Check llvm.memcpy is versioned into llvm.memcpy.inline and the control flow is handled correctly.
define void @memcpy_versioning_2(i64 %size) {
; CHECK-LABEL: @memcpy_versioning_2(
; CHECK-NEXT:  bb0:
; CHECK-NEXT:    [[VAL:%.*]] = alloca i8, align 4
; CHECK-NEXT:    store i32 42, ptr [[VAL]], align 4
; CHECK-NEXT:    [[VAL1:%.*]] = alloca i8, align 4
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[MEMCPY_SIZE_CMP:%.*]] = icmp ule i64 [[SIZE:%.*]], 128
; CHECK-NEXT:    br i1 [[MEMCPY_SIZE_CMP]], label [[CALL_MEMCPY_INLINE:%.*]], label [[CALL_MEMCPY_ORIGINAL:%.*]]
; CHECK:       call.memcpy.original:
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[VAL1]], ptr align 4 [[VAL]], i64 [[SIZE]], i1 false)
; CHECK-NEXT:    br label [[CALL_MEMCPY_MERGE:%.*]]
; CHECK:       call.memcpy.inline:
; CHECK-NEXT:    call void @llvm.memcpy.inline.p0.p0.i64(ptr align 4 [[VAL1]], ptr align 4 [[VAL]], i64 [[SIZE]], i1 false)
; CHECK-NEXT:    br label [[CALL_MEMCPY_MERGE]]
; CHECK:       call.memcpy.merge:
; CHECK-NEXT:    store i32 13, ptr [[VAL]], align 4
; CHECK-NEXT:    call void @foo(ptr [[VAL1]])
; CHECK-NEXT:    ret void
;
bb0:
  %val = alloca i8, align 4
  store i32 42, ptr %val
  %val1 = alloca i8, align 4
  br label %bb1
 
bb1:
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %val1, ptr align 4 %val, i64 %size, i1 false)
  store i32 13, ptr %val
  call void @foo(ptr %val1)
  ret void
}
