; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=unknown -passes=loop-data-prefetch --indirect-load-prefetch=true --prefetch-distance=512 --outer-loop-prefetch=true --random-access-prefetch-only=true -disable-direct-prefetch -S | FileCheck %s

target datalayout = "e-m:e-p:32:32-Fi8-i64:64:128-a:0:32-n32-S64"
target triple = "armv8a-unknown-linux-gun"

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare i32 @llvm.aarch64.crc32w(i32, i32)

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(read, inaccessiblemem: none)
define dso_local arm_aapcscc noundef i32 @_z12matchcolumnsPPiS_ii(ptr nocapture noundef readonly %A, ptr nocapture noundef readnone %key, i32 noundef %index, i32 noundef %count) local_unnamed_addr {
; CHECK-LABEL: @_z12matchcolumnsPPiS_ii(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds ptr, ptr [[A:%.*]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 4
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret i32 [[SUM_1_LCSSA:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[SUM_040:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[SUM_1_LCSSA]], [[FOR_COND_CLEANUP4:%.*]] ]
; CHECK-NEXT:    [[I_039:%.*]] = phi i32 [ 0, [[ENTRY]] ], [ [[INC17:%.*]], [[FOR_COND_CLEANUP4]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[I_039]], 19
; CHECK-NEXT:    [[TMP3:%.*]] = icmp slt i32 [[TMP2]], 99
; CHECK-NEXT:    [[TMP4:%.*]] = select i1 [[TMP3]], i32 [[TMP2]], i32 99
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds ptr, ptr [[A]], i32 [[I_039]]
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[CMP336:%.*]] = icmp sgt i32 [[TMP6]], 0
; CHECK-NEXT:    br i1 [[CMP336]], label [[PREFETCH_FOR_BODY5_PREHEADER:%.*]], label [[FOR_COND_CLEANUP4]]
; CHECK:       prefetch.for.body5.preheader:
; CHECK-NEXT:    br label [[PREFETCH_FOR_BODY5:%.*]]
; CHECK:       prefetch.for.body5:
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = tail call i32 @llvm.aarch64.crc32w(i32 [[TMP8]], i32 -1)
; CHECK-NEXT:    [[TMP10:%.*]] = and i32 [[TMP9]], 255
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 [[TMP10]]
; CHECK-NEXT:    call void @llvm.prefetch.p0(ptr [[TMP11]], i32 0, i32 3, i32 1)
; CHECK-NEXT:    br label [[PREFETCH_END:%.*]]
; CHECK:       prefetch.end:
; CHECK-NEXT:    br label [[FOR_BODY5_PREHEADER:%.*]]
; CHECK:       for.body5.preheader:
; CHECK-NEXT:    br label [[FOR_BODY5:%.*]]
; CHECK:       for.cond.cleanup4.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP4]]
; CHECK:       for.cond.cleanup4:
; CHECK-NEXT:    [[SUM_1_LCSSA]] = phi i32 [ [[SUM_040]], [[FOR_BODY]] ], [ [[ADD:%.*]], [[FOR_COND_CLEANUP4_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[INC17]] = add nuw nsw i32 [[I_039]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC17]], 100
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]]
; CHECK:       for.body5:
; CHECK-NEXT:    [[J_038:%.*]] = phi i32 [ [[INC15:%.*]], [[IF_END:%.*]] ], [ 0, [[FOR_BODY5_PREHEADER]] ]
; CHECK-NEXT:    [[SUM_137:%.*]] = phi i32 [ [[ADD]], [[IF_END]] ], [ [[SUM_040]], [[FOR_BODY5_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds ptr, ptr [[A]], i32 [[J_038]]
; CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[ARRAYIDX6]], align 4
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds i32, ptr [[TMP12]], i32 [[I_039]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX7]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.aarch64.crc32w(i32 [[TMP13]], i32 -1)
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[TMP14]], 255
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds i32, ptr [[TMP12]], i32 [[AND]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX8]], align 4
; CHECK-NEXT:    [[CMP9_NOT:%.*]] = icmp eq i32 [[TMP15]], [[INDEX:%.*]]
; CHECK-NEXT:    br i1 [[CMP9_NOT]], label [[IF_END]], label [[DO_BODY_PREHEADER:%.*]]
; CHECK:       do.body.preheader:
; CHECK-NEXT:    br label [[DO_BODY:%.*]]
; CHECK:       do.body:
; CHECK-NEXT:    [[J_1:%.*]] = phi i32 [ [[INC10:%.*]], [[DO_BODY]] ], [ [[J_038]], [[DO_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[AKEY_0:%.*]] = phi i32 [ [[INC:%.*]], [[DO_BODY]] ], [ [[AND]], [[DO_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[AKEY_0]], 1
; CHECK-NEXT:    [[INC10]] = add nsw i32 [[J_1]], 1
; CHECK-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds ptr, ptr [[A]], i32 [[INC10]]
; CHECK-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[ARRAYIDX11]], align 4
; CHECK-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds i32, ptr [[TMP16]], i32 [[INC]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[ARRAYIDX12]], align 4
; CHECK-NEXT:    [[CMP13_NOT:%.*]] = icmp eq i32 [[TMP17]], [[INDEX]]
; CHECK-NEXT:    br i1 [[CMP13_NOT]], label [[IF_END_LOOPEXIT:%.*]], label [[DO_BODY]]
; CHECK:       if.end.loopexit:
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[J_2:%.*]] = phi i32 [ [[J_038]], [[FOR_BODY5]] ], [ [[INC10]], [[IF_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[B_0:%.*]] = phi ptr [ [[TMP12]], [[FOR_BODY5]] ], [ [[TMP16]], [[IF_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[AKEY_1:%.*]] = phi i32 [ [[AND]], [[FOR_BODY5]] ], [ [[INC]], [[IF_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds i32, ptr [[B_0]], i32 [[AKEY_1]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i32, ptr [[ARRAYIDX14]], align 4
; CHECK-NEXT:    [[ADD]] = add nsw i32 [[TMP18]], [[SUM_137]]
; CHECK-NEXT:    [[INC15]] = add nsw i32 [[J_2]], 1
; CHECK-NEXT:    [[CMP3:%.*]] = icmp slt i32 [[INC15]], [[TMP6]]
; CHECK-NEXT:    br i1 [[CMP3]], label [[FOR_BODY5]], label [[FOR_COND_CLEANUP4_LOOPEXIT]]
;
entry:
  br label %for.body

for.cond.cleanup:
  ret i32 %sum.1.lcssa

for.body:
  %sum.040 = phi i32 [ 0, %entry ], [ %sum.1.lcssa, %for.cond.cleanup4 ]
  %i.039 = phi i32 [ 0, %entry ], [ %inc17, %for.cond.cleanup4 ]
  %arrayidx = getelementptr inbounds ptr, ptr %A, i32 %i.039
  %0 = load ptr, ptr %arrayidx, align 4
  %1 = load i32, ptr %0, align 4
  %cmp336 = icmp sgt i32 %1, 0
  br i1 %cmp336, label %for.body5, label %for.cond.cleanup4

for.cond.cleanup4:
  %sum.1.lcssa = phi i32 [ %sum.040, %for.body ], [ %add, %if.end ]
  %inc17 = add nuw nsw i32 %i.039, 1
  %exitcond.not = icmp eq i32 %inc17, 100
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body

for.body5:
  %j.038 = phi i32 [ %inc15, %if.end ], [ 0, %for.body ]
  %sum.137 = phi i32 [ %add, %if.end ], [ %sum.040, %for.body ]
  %arrayidx6 = getelementptr inbounds ptr, ptr %A, i32 %j.038
  %2 = load ptr, ptr %arrayidx6, align 4
  %arrayidx7 = getelementptr inbounds i32, ptr %2, i32 %i.039
  %3 = load i32, ptr %arrayidx7, align 4
  %4 = tail call i32 @llvm.aarch64.crc32w(i32 %3, i32 -1)
  %and = and i32 %4, 255
  %arrayidx8 = getelementptr inbounds i32, ptr %2, i32 %and
  %5 = load i32, ptr %arrayidx8, align 4
  %cmp9.not = icmp eq i32 %5, %index
  br i1 %cmp9.not, label %if.end, label %do.body

do.body:
  %j.1 = phi i32 [ %inc10, %do.body ], [ %j.038, %for.body5 ]
  %AKey.0 = phi i32 [ %inc, %do.body ], [ %and, %for.body5 ]
  %inc = add nuw nsw i32 %AKey.0, 1
  %inc10 = add nsw i32 %j.1, 1
  %arrayidx11 = getelementptr inbounds ptr, ptr %A, i32 %inc10
  %6 = load ptr, ptr %arrayidx11, align 4
  %arrayidx12 = getelementptr inbounds i32, ptr %6, i32 %inc
  %7 = load i32, ptr %arrayidx12, align 4
  %cmp13.not = icmp eq i32 %7, %index
  br i1 %cmp13.not, label %if.end, label %do.body

if.end:
  %j.2 = phi i32 [ %j.038, %for.body5 ], [ %inc10, %do.body ]
  %B.0 = phi ptr [ %2, %for.body5 ], [ %6, %do.body ]
  %AKey.1 = phi i32 [ %and, %for.body5 ], [ %inc, %do.body ]
  %arrayidx14 = getelementptr inbounds i32, ptr %B.0, i32 %AKey.1
  %8 = load i32, ptr %arrayidx14, align 4
  %add = add nsw i32 %8, %sum.137
  %inc15 = add nsw i32 %j.2, 1
  %cmp3 = icmp slt i32 %inc15, %1
  br i1 %cmp3, label %for.body5, label %for.cond.cleanup4
}
