; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=unknown -passes=loop-data-prefetch --indirect-load-prefetch=true --prefetch-distance=512 --outer-loop-prefetch=true --random-access-prefetch-only=true -disable-direct-prefetch -S | FileCheck %s

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gun"

declare i32 @llvm.aarch64.crc32w(i32, i32)

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(argmem: read) uwtable
define dso_local noundef i32 @_Z12matchcolumnsPiiS_ii(ptr nocapture noundef readonly %A, i32 noundef %B, ptr nocapture noundef readonly %Key, i32 noundef %index, i32 noundef %count) {
; CHECK-LABEL: @_Z12matchcolumnsPiiS_ii(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret i32 [[ADD:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV22:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDVARS_IV_NEXT23:%.*]], [[IF_END:%.*]] ]
; CHECK-NEXT:    [[SUM_020:%.*]] = phi i32 [ 0, [[ENTRY]] ], [ [[ADD]], [[IF_END]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDVARS_IV22]], 22
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt i64 [[TMP0]], 99
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i64 [[TMP0]], i64 99
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[INDVARS_IV22]], 44
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDVARS_IV22]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[TMP2]]
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    call void @llvm.prefetch.p0(ptr [[TMP4]], i32 0, i32 3, i32 1)
; CHECK-NEXT:    [[TMP8:%.*]] = tail call i32 @llvm.aarch64.crc32w(i32 [[TMP6]], i32 -1)
; CHECK-NEXT:    [[TMP9:%.*]] = tail call i32 @llvm.aarch64.crc32w(i32 [[TMP7]], i32 -1)
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[TMP8]], 255
; CHECK-NEXT:    [[TMP10:%.*]] = and i32 [[TMP9]], 255
; CHECK-NEXT:    [[IDXPROM1:%.*]] = zext i32 [[AND]] to i64
; CHECK-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[KEY:%.*]], i64 [[IDXPROM1]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[KEY]], i64 [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
; CHECK-NEXT:    call void @llvm.prefetch.p0(ptr [[TMP12]], i32 0, i32 3, i32 1)
; CHECK-NEXT:    [[CMP3_NOT:%.*]] = icmp eq i32 [[TMP14]], [[B:%.*]]
; CHECK-NEXT:    br i1 [[CMP3_NOT]], label [[IF_END]], label [[DO_BODY_PREHEADER:%.*]]
; CHECK:       do.body.preheader:
; CHECK-NEXT:    br label [[DO_BODY:%.*]]
; CHECK:       do.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[DO_BODY]] ], [ [[IDXPROM1]], [[DO_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds i32, ptr [[KEY]], i64 [[INDVARS_IV_NEXT]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX5]], align 4
; CHECK-NEXT:    [[CMP6_NOT:%.*]] = icmp eq i32 [[TMP15]], [[B]]
; CHECK-NEXT:    br i1 [[CMP6_NOT]], label [[IF_END_LOOPEXIT:%.*]], label [[DO_BODY]]
; CHECK:       if.end.loopexit:
; CHECK-NEXT:    [[TMP16:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[AKEY_1:%.*]] = phi i32 [ [[AND]], [[FOR_BODY]] ], [ [[TMP16]], [[IF_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[IDXPROM7:%.*]] = sext i32 [[AKEY_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[IDXPROM7]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[ARRAYIDX8]], align 4
; CHECK-NEXT:    [[ADD]] = add nsw i32 [[TMP17]], [[SUM_020]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT23]] = add nuw nsw i64 [[INDVARS_IV22]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT23]], 100
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:
  ret i32 %add

for.body:
  %indvars.iv22 = phi i64 [ 0, %entry ], [ %indvars.iv.next23, %if.end ]
  %sum.020 = phi i32 [ 0, %entry ], [ %add, %if.end ]
  %arrayidx = getelementptr inbounds i32, ptr %A, i64 %indvars.iv22
  %0 = load i32, ptr %arrayidx, align 4
  %1 = tail call i32 @llvm.aarch64.crc32w(i32 %0, i32 -1)
  %and = and i32 %1, 255
  %idxprom1 = zext i32 %and to i64
  %arrayidx2 = getelementptr inbounds i32, ptr %Key, i64 %idxprom1
  %2 = load i32, ptr %arrayidx2, align 4
  %cmp3.not = icmp eq i32 %2, %B
  br i1 %cmp3.not, label %if.end, label %do.body

do.body:
  %indvars.iv = phi i64 [ %idxprom1, %for.body ], [ %indvars.iv.next, %do.body ]
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %arrayidx5 = getelementptr inbounds i32, ptr %Key, i64 %indvars.iv.next
  %3 = load i32, ptr %arrayidx5, align 4
  %cmp6.not = icmp eq i32 %3, %B
  br i1 %cmp6.not, label %if.end.loopexit, label %do.body

if.end.loopexit:
  %4 = trunc i64 %indvars.iv.next to i32
  br label %if.end

if.end:
  %AKey.1 = phi i32 [ %and, %for.body ], [ %4, %if.end.loopexit ]
  %idxprom7 = sext i32 %AKey.1 to i64
  %arrayidx8 = getelementptr inbounds i32, ptr %A, i64 %idxprom7
  %5 = load i32, ptr %arrayidx8, align 4
  %add = add nsw i32 %5, %sum.020
  %indvars.iv.next23 = add nuw nsw i64 %indvars.iv22, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next23, 100
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
